In [1]:
import numpy as np
from numpy import ndarray

Calculations that can be performed

In [2]:
print("Welcome to Matrix Calculator. Choose any of the following options")
print()
print("(1) To add matrices")
print("(2) To multiply matrices")
print("(3) To find the inverse of a matrix")
print("(5) To find the determinant of a matrix")
print("(6) To find the eigenvalues & eigenvectors of a matrix")
print()
choice = int(input())

Welcome to Matrix Calculator. Choose any of the following options

(1) To add matrices
(2) To multiply matrices
(3) To find the inverse of a matrix
(5) To find the determinant of a matrix
(6) To find the eigenvalues & eigenvectors of a matrix



Some Necessary Functions

In [ ]:
#Matrix Extractor for user input - not required
'''def array_extractor(A: list):
    rows, columns = len(A), len(A[0])
    arr = np.empty(shape=(rows, columns))

    for row in range(rows):
        for column in range(columns):
            arr[row, column] = A[row][column]
    
    return arr'''

#Dimension checker for addition of matrices
def dim_check_add(A: ndarray, B: ndarray) -> bool:
        if A.shape == B.shape:
            return True
        return False

#Dimension checker for multiplication of matrices
def dim_check_mul(A: ndarray, B: ndarray) -> bool:
    rows_B, columns_A = A.shape[1], B.shape[0]
    if rows_B == columns_A:
         return True
    return False

#Check if determinant is possible
def is_square(A: ndarray):
     if A.shape[0] == A.shape[1]:
          return True
     return False

#Check if inverse is possible
def is_invertible(A: ndarray):
     if is_square(A) and np.linalg.det(A) != 0:
          return True
     return False          
          

ADDITION

In [14]:
if choice == 1:
    #No. of matrices
    num = int(input("How many matrices do you have? "))

    print("Enter a row of a matrix, separarted by space, in the input field")
    print("Enter x to stop entering the rows for a matrix")
    print()

    row_count = 0   #To show user the row number he is entering
    mtx = []    #For extracting the matrices

    #Asking for num matrices
    for i in range(num):
        print(f"Matrix {i+1}")
        
        #Asking for rows of the matrix
        while True:
            row_count += 1
            row = input(f"Enter row {row_count}: ")

            #Checking if he wants to terminate entering rows
            if row.lower() == 'x':
                break
            
            elements = row.split()  #Each element of the row
            elements = list(map(int, elements)) #Converting the elements to integer
            mtx.append(elements)    #Appending each row to mtx to finally extract the mtx

        #Initialising mtx_add
        if i==0:
            rows, columns = row_count-1, len(elements)
            mtx_add = np.zeros(shape = (rows, columns))

        arr = np.array(mtx) #Converting list to array

        #Checking dimensions
        if dim_check_add(mtx_add, arr):
            mtx_add += arr
        else:
            print("The matrices are not of the same dimension")
        
        row_count, mtx = 0, []  #Initial conditions

        print(arr)
        print()
    
    print("Sum: ", mtx_add)

    
    '''arr = np.array(eval(input("Enter matrix 1: ")))

    #Using mtx_add for summing matrices and assigning 1st array value to mtx_add
    mtx_add = arr
    count = 2  #count variable for telling user the array number that he is entering

    #Continuing the loop until user exits
    while True:
        inp = eval(input(f"Enter matrix {count}: "))

        #If user wants to stop entering arrays
        if type(inp) == str:
            if inp.lower() == 'x':
                break
            else:
                print("Invalid Input")
                continue
        
        #Making numpy array from user input
        arr = np.array(inp)

        #Checking whether arrays have same dimension
        if dim_check_add(mtx_add, arr):
            mtx_add += arr
        else:
            print("ERROR! The arrays are not of same dimension")
            print()
            continue

        count += 1  #incrementing count'''

    
    

Enter a row of a matrix, separarted by space, in the input field
Enter x to stop entering the rows for a matrix

Matrix 1
[[1 2 3]
 [4 5 6]]

Matrix 2
[[1 2 3]
 [4 5 6]]

Sum:  [[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [6]:
arr_1 = np.array([[1,2,3], [4,5,6]])
arr_2 = [[1,3,5], [5,7,9]]
arr_1.shape

(2, 3)

[[1 2 3 4]
 [1 3 5 7]]


[1, 2, 3, 4]
