In [63]:
import numpy as np
from numpy import ndarray
from sympy import Matrix
import scipy.linalg as sclinalg

Calculations that can be performed

In [2]:
print("Welcome to Matrix Calculator. Choose any of the following options")
print()
print("(1) To add matrices")
print("(2) To multiply matrices")
print("(3) To find the inverse of a matrix")
print("(4) To find the determinant of a matrix")
print("(5) To find the eigenvalues & eigenvectors of a matrix")
print("(6) To find powers of a matrix")
print("(7) To find the functions operated on a matrix")
print()
choice = int(input())

intro_text = "Enter a row of a matrix, separarted by space, in the input field\nEnter x to stop entering the rows for a matrix\n"

Welcome to Matrix Calculator. Choose any of the following options

(1) To add matrices
(2) To multiply matrices
(3) To find the inverse of a matrix
(4) To find the determinant of a matrix
(5) To find the eigenvalues & eigenvectors of a matrix
(6) To find powers of a matrix
(7) To find the functions operated on a matrix



Function for extracting Matrix from the User

In [3]:
def matrix_extractor() -> ndarray:
    """
    Asks for a matrix from the user in the form of rows for 1 input field.

    Returns:
    tuple: (The array entered by the user, (dimensions of the array))
    """
    row_count, mtx = 0, []

    #Asking for rows of the matrix
    while True:
        row_count += 1  #Incrementing row_count
        row = input(f"Enter row {row_count}: ")

        #Checking if user wants to terminate entering rows
        if row.lower() == 'x':
            break
        
        elements = row.split()  #Each element of the row
        elements = list(map(int, elements)) #Converting the elements to integer
        mtx.append(elements)    #Appending each row to mtx to finally extract the mtx
          
    arr = np.array(mtx)

    return arr

Some Necessary Functions

In [4]:
#Dimension checker for addition of matrices
def dim_check_add(A: ndarray, B: ndarray) -> bool:
    """
    Checks if the dimensions of 2 matrices to be added are correct
    Parameters:
    A(ndarray): 1st array
    B(ndarray): 2nd array
    Returns:
    bool: True if correct; False otherwise
    """
    if A.shape == B.shape:
        return True
    return False

#Dimension checker for multiplication of matrices
def dim_check_mul(A: ndarray, B: ndarray) -> bool:
    """
    Checks if the dimensions of 2 matrices to be multiplied are correct

    Parameters:
    A(ndarray): 1st array
    B(ndarray): 2nd array

    Returns:
    bool: True if correct; False otherwise
    """
    rows_B, columns_A = A.shape[1], B.shape[0]
    if rows_B == columns_A:
         return True
    return False

#Check if determinant is possible
def is_square(A: ndarray):
    """
    Checks if it is a square matrix
    Parameters:
    A(ndarray): array to be checked
    Returns:
    bool: True if square; False otherwise
    """
    if A.shape[0] == A.shape[1]:
         return True
    return False

#Check if inverse is possible
def is_invertible(A: ndarray):
    """
    Checks if inverse is possible
    Parameters:
    A(ndarray): array to be checked
    Returns:
    bool: True if possible; False otherwise
    """
    if is_square(A) and np.linalg.det(A) != 0:
         return True
    return False          

Function for Addition/Multiplication

In [5]:
def add_multiply(dim_checker, is_add: bool):
    """
    Function for adding/multiplying matrices

    Parameters:
    dim_checker(function): The dimension checking function
    is_add(bool): True for addition; False for multiplication

    Returns:
    ndarray: The resultant array/matrix
    """
    num = int(input("How many matrices do you have? ")) #No. of matrices

    print(intro_text)
    print()

    #Asking for num no. of matrices
    for i in range(num):
        print(f"Matrix {i+1}")

        arr = matrix_extractor()
        print(arr)
        print()
        rows, columns = arr.shape
        
        #Initialising result_mtx once
        if i==0:
            if is_add == True:
                result_mtx = np.zeros(shape = (rows, columns))  #Initial zero mtx for addition
            else:
                result_mtx = np.identity(rows)   #Initial identity mtc for multiplication

        #Checking dimensions
        if dim_checker(result_mtx, arr):
            if is_add == True:
                result_mtx += arr
            else:
                result_mtx = result_mtx@arr
        else:
            return "The matrices are not of correct dimensions"
    
    return f"Result:\n{result_mtx}"

Addition/Multiplication

In [6]:
if choice == 1: #Addition
    result = add_multiply(dim_checker=dim_check_add, is_add=True)
    print(result)

elif choice == 2:   #Multiplication
    result = add_multiply(dim_checker=dim_check_mul, is_add=False)
    print(result)

User Enters the entire matrix in 1 input cell

In [7]:
'''arr = np.array(eval(input("Enter matrix 1: ")))

    #Using mtx_add for summing matrices and assigning 1st array value to mtx_add
    mtx_add = arr
    count = 2  #count variable for telling user the array number that he is entering

    #Continuing the loop until user exits
    while True:
        inp = eval(input(f"Enter matrix {count}: "))

        #If user wants to stop entering arrays
        if type(inp) == str:
            if inp.lower() == 'x':
                break
            else:
                print("Invalid Input")
                continue
        
        #Making numpy array from user input
        arr = np.array(inp)

        #Checking whether arrays have same dimension
        if dim_check_add(mtx_add, arr):
            mtx_add += arr
        else:
            print("ERROR! The arrays are not of same dimension")
            print()
            continue

        count += 1  #incrementing count'''

'arr = np.array(eval(input("Enter matrix 1: ")))\n\n    #Using mtx_add for summing matrices and assigning 1st array value to mtx_add\n    mtx_add = arr\n    count = 2  #count variable for telling user the array number that he is entering\n\n    #Continuing the loop until user exits\n    while True:\n        inp = eval(input(f"Enter matrix {count}: "))\n\n        #If user wants to stop entering arrays\n        if type(inp) == str:\n            if inp.lower() == \'x\':\n                break\n            else:\n                print("Invalid Input")\n                continue\n\n        #Making numpy array from user input\n        arr = np.array(inp)\n\n        #Checking whether arrays have same dimension\n        if dim_check_add(mtx_add, arr):\n            mtx_add += arr\n        else:\n            print("ERROR! The arrays are not of same dimension")\n            print()\n            continue\n\n        count += 1  #incrementing count'

Function for finding inverse of a matrix

In [8]:
def inverse(matrix: ndarray):
    """
    Finds the inverse of a matrix, if invertible

    Parameters:
    matrix(ndarray): The matrix whose inverse is required

    Returns:
    ndarray: Inverse of matrix, if invertible
    """
    if is_invertible(matrix):
        return f"Result:\n{np.linalg.inv(matrix)}"
    elif not is_square(matrix):
        return "The matrix is not square so determinant cannot be calculated"
    else:
        return "Matrix is not invertible as determinant is 0"

Inverse/Determinant

In [9]:
if choice == 3: #Inverse
    print(intro_text)
    mtx = matrix_extractor()
    print("Matrix:\n", mtx)
    print()

    result = inverse(mtx)
    print(result)

elif choice == 4:   #Determinant
    print(intro_text)
    mtx = matrix_extractor()
    print("Matrix:\n", mtx)
    print()

    if is_square(mtx):
        result = np.linalg.det(mtx)
        print(f"Result:\n{result}")
    else:
        print("The matrix is not square so determinant cannot be calculated")

Eigenvalues/Eigenvectors

In [ ]:
if choice == 5: #Eigenvalues and eigenvectors of matrix
    print(intro_text)
    mtx = matrix_extractor()
    print("Matrix:\n", mtx)
    print()

    if is_square(mtx):
        mtx = Matrix(mtx)
        eigen_data = mtx.eigenvects()   #Each element of eigen_data = (eigenvals, algebraic_multiplicity, list(Matrix(eigenvectors)))

        for i in range(len(eigen_data)):
            eigenvals = eigen_data[i][0]
            eigenvects = eigen_data[i][2]
            eigenvects = np.array(eigenvects[0].tolist())   #Array of eigenvectors

            print(f"Eigenvalue {i+1}: {eigenvals}")
            print(f"Eigenvector {i+1}:\n{eigenvects}")
            print()
    
    else:
        print("Eigenvalues/eigenvectors cannot be computed for non-square matrices")

Enter a row of a matrix, separarted by space, in the input field
Enter x to stop entering the rows for a matrix

Matrix:
 [[1 2]
 [5 4]]

Eigenvalue 1: -1
Eigenvector 1:
[[-1]
 [1]]

Eigenvalue 2: 6
Eigenvector 2:
[[2/5]
 [1]]



Powers of a Matrix

In [ ]:
choice = 6

if choice == 6:
    print(intro_text)
    print()

    mtx = matrix_extractor()
    print(f"Matrix:\n{mtx}")
    print()

    if is_square(mtx):
        pow = int(input("Enter the power of the matrix: "))
    
        eigenvals, eigenvects = np.linalg.eig(mtx)
    
        #mtx = PDP^(-1)     mtx^n = P(D^n)P^(-1)
        D = np.diag(eigenvals)
        P = eigenvects
        P_inv = np.linalg.inv(P)
        D_pow = np.linalg.matrix_power(D, pow)
        
        result = P@D_pow@P_inv
        print(f"Result:\n{result}")

    else:
        print("Powers of non-sqaure matrices cannot be calculated")

Enter a row of a matrix, separarted by space, in the input field
Enter x to stop entering the rows for a matrix


Matrix:
[[1 2]
 [5 4]]

Result:
[[ 61.  62.]
 [155. 154.]]


Operations on a matrix

In [ ]:
if choice == 7:
    print("Choose from one of the following operaions: ")
    print("(1) sin")
    print("(2) cos")
    print("(3) exponential")
    print("(4) logarithm")
    print("(5) sinh")
    print("(6) cosh")

    choice = int(input())
    print()

    mtx = matrix_extractor()
    print(mtx)
    print()


In [54]:
arr = np.array([[1,2], [5,4]])
# eigenvals, eigenvects = np.linalg.eig(arr)
# print(eigenvals)
# print(type(eigenvals))
np.linalg.matrix_power(arr, 3)

array([[ 61,  62],
       [155, 154]])

In [ ]:
arr_1 = np.array([[1,2,3], [4,5,6]])
arr_2 = [[1,3,5], [5,7,9]]
arr_1.shape

(2, 3)

In [ ]:
def add(a, b):
    return a+b

def applier(func, a, b):
    return func(a,b)

print(applier(add, 2, 4))

6


In [46]:
arr = np.array(tuple(i for i in range(4))).reshape(2,2)
print(arr)


[[0 1]
 [2 3]]
